platform :ios, '9.0'
inhibit_all_warnings!
use_frameworks!

target 'JoeyPak' do
  pod 'Texture'
  pod 'FBSDKLoginKit'
  pod 'ParticleExtensions', :git => 'https://github.com/ParticleApps/Extensions.git'
end
